export default {
	namespaced:true,
	state: {
		datas:{
			'fcgg':{
				banners:[{
					src:'../static/fcgg.jpg',
					text:'杭州·富春硅谷'
				}],
				titleImg:'../static/ft-1.png',
				textImg1:'../static/ft-2.png',
				textImg2:'../static/ft-3.png',
				textImg3:'../static/ft-4.png',
				textImg4:'../static/ft-5.png',
				textImg5:'../static/ft-6.png',
				search:'../static/search.png',
				title:'杭州·富春硅谷',
				imgs1:[
					'../static/fcgg-1.jpg',
					'../static/fcgg-2.jpg',
					'../static/fcgg-3.png'
				],
				name1:'项目简介：',
				content1:[
					'富春硅谷，是由位列全国产业地产第十八强的百富东方投资集团倾力打造，是产业地产与城市发展相结合的典范项目，也是富阳新一轮产业兴市的首个重量级项目',
					'2013年落子杭州西部智慧产业核心区——银湖科技城，紧邻建设中的地铁6号线，总投资超30亿元',
					'整个项目拥有约70万㎡的总建筑面积，约50万㎡产业办公，约10万㎡低密住宅，以及约10万方创客商业的庞大规模，以“全硅谷”理念规划打造集科技、商务、研发、办公、生活、休闲、娱乐为一体的城市产业综合体，建成后将成为整个银湖科技城的核心引擎！'
				],
				text1:'/ 产品类型',
				content2:[{
					img:"../static/fcgg-4.png",
					title:'Market',
					name:'商业',
					content:'蔚蓝创新天地打造国际型VMALL商业街区—蔚蓝新天地，囊括休闲、购物、娱乐为一体，填补区域商业消费空白，以时尚、生态、艺术、活力、休闲为体验理念，最终实现一站式，全客群、全天候的休闲购物目的地，打造城阳“未来之城”商业新中心。'
				},{
					img:"../static/fcgg-5.jpg",
					title:'Community',
					name:'住宅区',
					content:'蔚蓝创新天地住宅产品系，包括精英高层蔚蓝观邸、中心洋房、领袖级mini墅澜公馆、总裁级别墅等，将生活、商务办公与潮流商业无缝衔接。'
				},{
					img:"../static/fcgg-6.jpg",
					title:'Office',
					name:'产业',
					content:'打造U+智慧运营服务体系，以成长总顾问、人才根据地、政策给力者、事业合伙人、提效服务商、创新先行师、资本引路人、圈层俱乐部八重导师级专业服务身份助力企业腾飞。产品涵盖LOFT联合办公空间、城市甲级写字楼、定制级企业独栋。'
				}],
				text2:'/ 入驻情况',
				content3:[
					'../static/silicon_11_20.png',
					'../static/silicon_11_21.png',
					'../static/silicon_11_22.png',
					'../static/silicon_11_23.png',
					'../static/silicon_11_24.png',
					'../static/silicon_11_25.png',
					'../static/silicon_11_26.png',
					'../static/silicon_11_27.png',
					'../static/silicon_11_28.png',
					'../static/silicon_11_29.png',
					'../static/silicon_11_30.png',
					'../static/silicon_11_31.png'
				],
				text3:'/ 在线招商',
				content4:{
					banners:[{
						src:'../static/fcgg-7.jpg'
					},{
						src:'../static/fcgg-7.jpg'
					}]
				},
				text4:'/ 周边交通',
				content5:{
					infos:[{
						name:'地址信息',
						text:'青岛市城阳荟城路506号'
					},{
						name:"电话",
						text:'0532-67721602'
					}],
					map:{
						lng:113.951744,
						lat:22.543661,
						content:[{
							name:'地址',
							text:'青岛蔚蓝'
						},{
							name:'电话',
							text:'0755-22699622'
						},{
							name:'传真',
							text:'0532-67721602'
						}]
					}
				},
				text5:'/ 联系我们',
				content6:{
					imgs:[
						'../static/fcgg-9.png',
						'../static/fcgg-10.png',
						'../static/fcgg-11.png'
					],
					infos:[{
						name:'售楼电话：',
						text:'0532-87966888'
					}]
				}
			},
			'cbd':{
				banners:[{
					src:'../static/cbd.jpg',
					text:'重庆 · 璧山CBD'
				}],
				titleImg:'../static/ft-1.png',
				textImg1:'../static/ft-2.png',
				textImg2:'../static/ft-3.png',
				textImg3:'../static/ft-4.png',
				textImg4:'../static/ft-5.png',
				textImg5:'../static/ft-6.png',
				search:'../static/search.png',
				title:'杭州·富春硅谷',
				imgs1:[
					'../static/fcgg-1.jpg',
					'../static/fcgg-2.jpg'
				],
				name1:'项目简介：',
				content1:[
					'富春硅谷，是由位列全国产业地产第十八强的百富东方投资集团倾力打造，是产业地产与城市发展相结合的典范项目，也是富阳新一轮产业兴市的首个重量级项目',
					'2013年落子杭州西部智慧产业核心区——银湖科技城，紧邻建设中的地铁6号线，总投资超30亿元',
					'整个项目拥有约70万㎡的总建筑面积，约50万㎡产业办公，约10万㎡低密住宅，以及约10万方创客商业的庞大规模，以“全硅谷”理念规划打造集科技、商务、研发、办公、生活、休闲、娱乐为一体的城市产业综合体，建成后将成为整个银湖科技城的核心引擎！'
				],
				text1:'/ 产品类型',
				content2:[{
					img:"../static/fcgg-4.png",
					title:'Market',
					name:'商业',
					content:'蔚蓝创新天地打造国际型VMALL商业街区—蔚蓝新天地，囊括休闲、购物、娱乐为一体，填补区域商业消费空白，以时尚、生态、艺术、活力、休闲为体验理念，最终实现一站式，全客群、全天候的休闲购物目的地，打造城阳“未来之城”商业新中心。'
				},{
					img:"../static/fcgg-5.jpg",
					title:'Community',
					name:'住宅区',
					content:'蔚蓝创新天地住宅产品系，包括精英高层蔚蓝观邸、中心洋房、领袖级mini墅澜公馆、总裁级别墅等，将生活、商务办公与潮流商业无缝衔接。'
				},{
					img:"../static/fcgg-6.jpg",
					title:'Office',
					name:'产业',
					content:'打造U+智慧运营服务体系，以成长总顾问、人才根据地、政策给力者、事业合伙人、提效服务商、创新先行师、资本引路人、圈层俱乐部八重导师级专业服务身份助力企业腾飞。产品涵盖LOFT联合办公空间、城市甲级写字楼、定制级企业独栋。'
				}],
				text2:'/ 入驻情况',
				content3:[
					'../static/silicon_11_20.png',
					'../static/silicon_11_21.png',
					'../static/silicon_11_22.png',
					'../static/silicon_11_23.png',
					'../static/silicon_11_24.png',
					'../static/silicon_11_25.png',
					'../static/silicon_11_26.png',
					'../static/silicon_11_27.png',
					'../static/silicon_11_28.png',
					'../static/silicon_11_29.png',
					'../static/silicon_11_30.png',
					'../static/silicon_11_31.png'
				],
				text3:'/ 在线招商',
				content4:{
					banners:[{
						src:'../static/fcgg-7.jpg'
					},{
						src:'../static/fcgg-7.jpg'
					}]
				},
				text4:'/ 周边交通',
				content5:{
					infos:[{
						name:'地址信息',
						text:'青岛市城阳荟城路506号'
					},{
						name:"电话",
						text:'0532-67721602'
					}],
					map:{
						lng:113.951744,
						lat:22.543661,
						content:[{
							name:'地址',
							text:'青岛蔚蓝'
						},{
							name:'电话',
							text:'0755-22699622'
						},{
							name:'传真',
							text:'0532-67721602'
						}]
					}
				},
				text5:'/ 联系我们',
				content6:{
					imgs:[
						'../static/fcgg-9.png',
						'../static/fcgg-10.png',
						'../static/fcgg-11.png'
					],
					infos:[{
						name:'售楼电话：',
						text:'0532-87966888'
					}]
				}
			},
			'wlcx':{
				banners:[{
					src:'../static/wlcx.jpg',
					text:'青岛 · 蔚蓝创新天地'
				}],
				titleImg:'../static/ft-1.png',
				textImg1:'../static/ft-2.png',
				textImg2:'../static/ft-3.png',
				textImg3:'../static/ft-4.png',
				textImg4:'../static/ft-5.png',
				textImg5:'../static/ft-6.png',
				search:'../static/search.png',
				title:'杭州·富春硅谷',
				imgs1:[
					'../static/fcgg-1.jpg',
					'../static/fcgg-2.jpg',
					'../static/fcgg-3.png'
				],
				name1:'项目简介：',
				content1:[
					'富春硅谷，是由位列全国产业地产第十八强的百富东方投资集团倾力打造，是产业地产与城市发展相结合的典范项目，也是富阳新一轮产业兴市的首个重量级项目',
					'2013年落子杭州西部智慧产业核心区——银湖科技城，紧邻建设中的地铁6号线，总投资超30亿元',
					'整个项目拥有约70万㎡的总建筑面积，约50万㎡产业办公，约10万㎡低密住宅，以及约10万方创客商业的庞大规模，以“全硅谷”理念规划打造集科技、商务、研发、办公、生活、休闲、娱乐为一体的城市产业综合体，建成后将成为整个银湖科技城的核心引擎！'
				],
				text1:'/ 产品类型',
				content2:[{
					img:"../static/fcgg-4.png",
					title:'Market',
					name:'商业',
					content:'蔚蓝创新天地打造国际型VMALL商业街区—蔚蓝新天地，囊括休闲、购物、娱乐为一体，填补区域商业消费空白，以时尚、生态、艺术、活力、休闲为体验理念，最终实现一站式，全客群、全天候的休闲购物目的地，打造城阳“未来之城”商业新中心。'
				},{
					img:"../static/fcgg-5.jpg",
					title:'Community',
					name:'住宅区',
					content:'蔚蓝创新天地住宅产品系，包括精英高层蔚蓝观邸、中心洋房、领袖级mini墅澜公馆、总裁级别墅等，将生活、商务办公与潮流商业无缝衔接。'
				},{
					img:"../static/fcgg-6.jpg",
					title:'Office',
					name:'产业',
					content:'打造U+智慧运营服务体系，以成长总顾问、人才根据地、政策给力者、事业合伙人、提效服务商、创新先行师、资本引路人、圈层俱乐部八重导师级专业服务身份助力企业腾飞。产品涵盖LOFT联合办公空间、城市甲级写字楼、定制级企业独栋。'
				}],
				text2:'/ 入驻情况',
				content3:[
					'../static/silicon_11_20.png',
					'../static/silicon_11_21.png',
					'../static/silicon_11_22.png',
					'../static/silicon_11_23.png',
					'../static/silicon_11_24.png',
					'../static/silicon_11_25.png',
					'../static/silicon_11_26.png',
					'../static/silicon_11_27.png',
					'../static/silicon_11_28.png',
					'../static/silicon_11_29.png'
				],
				text3:'/ 在线招商',
				content4:{
					banners:[{
						src:'../static/fcgg-7.jpg'
					},{
						src:'../static/fcgg-7.jpg'
					}]
				},
				text4:'/ 周边交通',
				content5:{
					infos:[{
						name:'地址信息',
						text:'青岛市城阳荟城路506号'
					},{
						name:"电话",
						text:'0532-67721602'
					}],
					map:{
						lng:113.951744,
						lat:22.543661,
						content:[{
							name:'地址',
							text:'青岛蔚蓝'
						},{
							name:'电话',
							text:'0755-22699622'
						}]
					}
				},
				text5:'/ 联系我们',
				content6:{
					imgs:[
						'../static/fcgg-9.png',
						'../static/fcgg-10.png'
					],
					infos:[{
						name:'售楼电话：',
						text:'0532-87966888'
					}]
				}
			}
		}
	},
	mutations: {

	},
	actions: {

	}
}